update-connection-to-mongo
fintegrate-practicum/communication pull request #54
Opened 2024-07-17 23:08 UTC by noah-cohen

update-connection-to-mongo

2024-07-17 23:09 UTC, noah-cohen commented
השוואתי בין orders שרץ מצוין ל communication שלא התחבר ל mongo
ולפי זה שינתי וזה מה שרץ טוב

2024-07-18 07:11 UTC, nechamaLearn requested changes

2024-07-18 07:11 UTC, nechamaLearn commented on src/app.module.ts
> +    try {
דברנו על זה שהtry catch כאן לא נכונים

2024-07-18 07:44 UTC, nechamaLearn approved these changes

2024-07-18 08:03 UTC, 475michalk approved these changes

2024-07-18 08:04 UTC, merged