Deploy to cloud run git
fintegrate-practicum/communication pull request #66
Opened 2024-07-28 23:04 UTC by 475michalk

add secrets in settings:
1. service_account
2. workload_identity_provider

2024-07-29 05:27 UTC, nechamaLearn requested changes

2024-07-29 05:27 UTC, nechamaLearn commented on github/workflows/deploy.yml
> +  REPO: communication
או Inventory או communication...
הייתי קוראת לrepo שם כללי יותר כדי לא להגיע למצב הזה

2024-07-29 05:27 UTC, nechamaLearn commented on github/workflows/deploy.yml
> +  IMAGE: communication
אין סיבה לא לקרוא לזה inventory

2024-07-29 05:27 UTC, nechamaLearn commented on github/workflows/deploy.yml
> +          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
יצרת אותם?

2024-07-29 06:23 UTC, 475michalk commented on github/workflows/deploy.yml
> +          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
כן יצרתי אותם בטח

2024-07-29 06:23 UTC, 475michalk commented on github/workflows/deploy.yml
> +  REPO: communication
נכון זה טעות שלי,

2024-07-29 06:32 UTC, noah-cohen submitted a review, later dismissed

2024-07-29 09:59 UTC, 475michalk commented on github/workflows/deploy.yml
> +  PROJECT_ID: fintegrate-fs1
בניתי את הפרויקט מחדש כדי לסדר את התהליך

2024-07-29 09:59 UTC, 475michalk commented on github/workflows/deploy.yml
> +          service_account: ${{ secrets.SERVICE_EMAIL }}
שמות חדשים

2024-07-29 10:07 UTC, 475michalk commented on github/workflows/deploy.yml
> +          service_account: ${{ secrets.SERVICE_EMAIL }}
וכמובן הוספתי אותם ב secrets

2024-07-29 23:06 UTC, nechamaLearn commented on github/workflows/deploy.yml
> +          service_account: ${{ secrets.SERVICE_EMAIL }}
למה שינית את השמות?
השם בשורה 32 הוא ממש לא נכון

2024-07-29 23:09 UTC, nechamaLearn requested changes

2024-07-29 23:09 UTC, nechamaLearn commented on github/workflows/deploy.yml
> +  PROJECT_ID: fintegrate-fs1
זה במקום הivory ההוא שהיה קודם, נכון

2024-07-29 23:09 UTC, nechamaLearn commented on github/workflows/deploy.yml
> +  IMAGE: fintegrate
הייתי מקימה תמונה שונה עבור כל repo של גיטהאב
שלא יהיה מצב של כפילות במקרה של העלאה בו זמנית

2024-07-29 23:10 UTC, 475michalk commented on github/workflows/deploy.yml
> +          service_account: ${{ secrets.SERVICE_EMAIL }}
אני אתקן את השם אבל המשתנה נכון בתוכו

2024-07-29 23:16 UTC, 475michalk commented
עשיתי שינויים--שיניתי את שם המשתנה למרות שהערך שלו נכון וגם שיניתי ב secrets בנוסף שיניתי את הimage שייהיה חלוקה

2024-07-30 07:11 UTC, nechamaLearn approved these changes

2024-07-30 07:17 UTC, merged